<?php

namespace App\Http\Requests\Manage;

use App\Support\SkipSegments;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class RecordingRequest extends FormRequest
{
    /**
     * Authorization runs through RecordingPolicy in the controller.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        $recording = $this->route('recording');

        return [
            'show_id' => ['nullable', 'integer', 'exists:shows,id'],
            'category_id' => ['nullable', 'integer', 'exists:categories,id'],
            'event_id' => ['nullable', 'integer', 'exists:events,id'],
            'title' => ['required', 'string', 'max:255'],
            'slug' => [
                'required',
                'string',
                'max:255',
                'regex:/^[a-z0-9-]+$/',
                Rule::unique('recordings', 'slug')->ignore($recording?->id),
            ],
            'description' => ['nullable', 'string', 'max:5000'],
            'date' => ['required', 'date'],
            // Left blank, ProcessRecordingJob reads it off the playlist.
            'duration' => ['nullable', 'integer', 'min:0'],

            // The cut: which slice of the source's archive this recording shows.
            // Distinct from the show's actual_start/actual_end, which record when it
            // aired. An end is required rather than optional, because a source that
            // stays online for the whole event never supplies one.
            'starts_at' => ['nullable', 'date', 'required_with:ends_at'],
            'ends_at' => ['nullable', 'date', 'required_with:starts_at', 'after:starts_at'],

            // Generated by ArchivePlaylistService for a cut, so it can only be required
            // when the recording is not one. Recordings registered from outside still
            // have to supply a playlist.
            'm3u8_url' => [
                Rule::requiredIf(fn () => ! $this->filled('starts_at')),
                'nullable', 'url', 'max:2048',
            ],
            // Offers, not edits: ranges the player may show a Skip button over. Kept
            // to seconds from the start of the recording, which is what the player
            // knows; overlaps are merged rather than refused.
            // The cut the form loaded against, so a save that missed a re-cut is
            // refused rather than writing skips that no longer line up.
            'cut_fingerprint' => ['nullable', 'string', 'max:64'],
            'skip_segments' => ['nullable', 'array', 'max:'.SkipSegments::MAX],
            'skip_segments.*.start' => ['required', 'numeric', 'min:0'],
            'skip_segments.*.end' => ['required', 'numeric', 'min:0', 'gt:skip_segments.*.start'],
            'skip_segments.*.label' => ['nullable', 'string', 'max:'.SkipSegments::LABEL_MAX],

            'thumbnail_path' => ['nullable', 'string', 'max:2048'],
            'is_published' => ['boolean'],
            'required_roles' => ['array'],
            'required_roles.*' => ['string', 'exists:roles,slug'],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'slug.regex' => 'The slug may only contain lowercase letters, numbers and dashes.',
        ];
    }

    protected function prepareForValidation(): void
    {
        // An empty select posts "", which would fail the integer rule rather than
        // reading as "no show".
        if ($this->input('category_id') === '') {
            $this->merge(['category_id' => null]);
        }

        if ($this->input('event_id') === '') {
            $this->merge(['event_id' => null]);
        }

        if ($this->input('show_id') === '') {
            $this->merge(['show_id' => null]);
        }

        if ($this->input('duration') === '') {
            $this->merge(['duration' => null]);
        }

        if ($this->has('skip_segments')) {
            $this->merge([
                'skip_segments' => SkipSegments::normalise($this->input('skip_segments')),
            ]);
        }
    }
}
