<script setup>
/**
 * Resolves the kebab-case icon names the server sends (Status::make, Action::icon,
 * Navigation items) to lucide components. Named imports keep this tree-shakeable, and
 * an unknown name renders nothing rather than throwing.
 */
import { computed } from 'vue';
import {
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  CircleX,
  Clock,
  Cloud,
  Code,
  Cog,
  Columns3,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  Film,
  Globe,
  Hand,
  HeartCrack,
  HeartPulse,
  ImageIcon,
  LayoutDashboard,
  Loader,
  Lock,
  LogOut,
  MessageSquare,
  Minus,
  Monitor,
  MonitorPlay,
  Paintbrush,
  PanelLeft,
  Pencil,
  Play,
  Plus,
  RadioTower,
  RefreshCw,
  Search,
  Send,
  Server,
  ShieldCheck,
  Signal,
  SignalZero,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Square,
  Trash2,
  TriangleAlert,
  Users,
  Video,
  X,
  Zap,
} from 'lucide-vue-next';

const icons = {
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bar-chart': BarChart3,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'check-circle': CircleCheck,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  'circle-x': CircleX,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  columns: Columns3,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  film: Film,
  globe: Globe,
  hand: Hand,
  'heart-crack': HeartCrack,
  'heart-pulse': HeartPulse,
  image: ImageIcon,
  'layout-dashboard': LayoutDashboard,
  loader: Loader,
  lock: Lock,
  'log-out': LogOut,
  'message-square': MessageSquare,
  minus: Minus,
  monitor: Monitor,
  'monitor-play': MonitorPlay,
  paintbrush: Paintbrush,
  'panel-left': PanelLeft,
  pencil: Pencil,
  play: Play,
  'play-circle': CirclePlay,
  plus: Plus,
  'radio-tower': RadioTower,
  'refresh-cw': RefreshCw,
  database: Database,
  search: Search,
  send: Send,
  server: Server,
  'shield-check': ShieldCheck,
  signal: Signal,
  'signal-zero': SignalZero,
  'sliders-horizontal': SlidersHorizontal,
  smile: Smile,
  sparkles: Sparkles,
  square: Square,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  users: Users,
  video: Video,
  x: X,
  zap: Zap,
};

const props = defineProps({
  name: { type: String, default: null },
  size: { type: Number, default: 14 },
});

const component = computed(() => (props.name ? icons[props.name] ?? null : null));
</script>

<template>
  <component :is="component" v-if="component" :size="size" :stroke-width="1.75" />
</template>
